<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<?php
/* @var $block \Magento\Backend\Block\Widget\Form\Renderer\Fieldset\Element */
$element = $block->getElement();
$note = $block->getNote() ? '<div class="note admin__field-note" id="' . $element->getId() . '-note">' . $block->getNote() . '</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox admin__control-checkbox' || $element->getExtType() == 'radio admin__control-radio';
$addOn = ($element->getBeforeElementHtml() || $element->getAfterElementHtml()) && !$element->getNoWrapAsAddon();
$fieldId = ($element->getHtmlContainerId()) ? ' id="' . $element->getHtmlContainerId() . '"' : '';
$fieldClass = "admin__field field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($addOn) ? ' with-addon' : '';
$fieldClass .= ($element->getRequired()) ? ' required _required' : '';
$fieldClass .= ($note) ? ' with-note' : '';
$fieldClass .= (!$element->getLabelHtml()) ? ' no-label' : '';

$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $block->getUiId('form-field', $element->getId())
    . ($element->getFieldExtraAttributes() ? ' ' . $element->getFieldExtraAttributes() : '');
?>

<?php
$elementToggleCode = $element->getToggleCode() ? $element->getToggleCode()
    : 'toggleValueElements(this, this.parentNode.parentNode.parentNode)';

if ($block->canDisplayUseDefault() && $block->usedDefault()) {
    $element->setDisabled(true);
}

?>

<?php if (!$element->getNoDisplay()): ?>
    <?php if ($element->getType() == 'hidden'): ?>
        <?= $element->getElementHtml() ?>
    <?php else: ?>
        <div<?= /* @escapeNotVerified */ $fieldAttributes ?>>
            <?php if ($elementBeforeLabel): ?>
                <?= $element->getElementHtml() ?>
                <?= $element->getLabelHtml('', $block->getScopeLabel()) ?>
                <?= /* @escapeNotVerified */ $note ?>
            <?php else: ?>
                <?= $element->getLabelHtml('', $block->getScopeLabel()) ?>
                <div class="admin__field-control control">
                    <?= /* @escapeNotVerified */ ($addOn) ? '<div class="admin__field">' . $element->getElementHtml() . '</div>' : $element->getElementHtml() ?>
                    <?= /* @escapeNotVerified */ $note ?>
                </div>
            <?php endif; ?>
            <div class="field-service">
                <?php if ($block->canDisplayUseDefault()): ?>
                    <label for="<?= $element->getHtmlId() ?>_default" class="choice use-default">
                        <input <?php if ($element->getReadonly()):?> disabled="disabled"<?php endif; ?> type="checkbox"
                                name="use_default[]"
                                class="use-default-control"
                                id="<?= $element->getHtmlId() ?>_default"
                            <?php if ($block->usedDefault()): ?> checked="checked"<?php endif; ?>
                                onclick="<?= /* @escapeNotVerified */ $elementToggleCode ?>"
                                value="<?= /* @escapeNotVerified */ $block->getAttributeCode() ?>"/>
                        <span class="use-default-label"><?= /* @escapeNotVerified */ __('Use Default Value') ?></span>
                    </label>
                <?php endif ?>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
