<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<?php
/** 
 * @var \Magento\Backend\Block\Widget\Form\Renderer\Fieldset\Element $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php
    $element = $block->getElement();
    $note = $block->getNote() ? '<div class="note admin__field-note" id="' 
        . $escaper->escapeHtmlAttr($element->getId()) 
        . '-note">' . $escaper->escapeHtml($block->getNote(), ['a', 'b', 'br']) 
        . '</div>' : '';
    $elementBeforeLabel = $element->getExtType() == 'checkbox admin__control-checkbox' || $element->getExtType() == 'radio admin__control-radio';
    $addOn = ($element->getBeforeElementHtml() || $element->getAfterElementHtml()) && !$element->getNoWrapAsAddon();
    $fieldId = ($element->getHtmlContainerId()) ? ' id="' . $element->getHtmlContainerId() . '"' : '';
    $fieldClass = "admin__field field field-{$element->getId()} {$element->getCssClass()}";
    $fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
    $fieldClass .= ($addOn) ? ' with-addon' : '';
    $fieldClass .= ($element->getRequired()) ? ' required _required' : '';
    $fieldClass .= ($note) ? ' with-note' : '';
    $fieldClass .= (!$element->getLabelHtml()) ? ' no-label' : '';

    $fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
        . $block->getUiId('form-field', $element->getId())
        . ($element->getFieldExtraAttributes() ? ' ' . $element->getFieldExtraAttributes() : '');
?>

<?php
$elementToggleCode = $element->getToggleCode() ? $element->getToggleCode()
    : 'toggleValueElements(this, this.parentNode.parentNode.parentNode)';

if ($block->canDisplayUseDefault() && $block->usedDefault()) {
    $element->setDisabled(true);
}

if ($block->canDisplayUseSystemValue() && $block->usedSystemValue()) {
    $element->setDisabled(true);
}

?>

<?php if (!$element->getNoDisplay()): ?>
    <?php if ($element->getType() == 'hidden'): ?>
        <?= $element->getElementHtml() ?>
    <?php else: ?>
        <div<?= /* @escapeNotVerified */ $fieldAttributes ?>>
            <?php if ($elementBeforeLabel): ?>
                <?= $element->getElementHtml() ?>
                <?= $element->getLabelHtml('', $block->getScopeLabel()) ?>
                <?= /* @escapeNotVerified */ $note ?>
            <?php else: ?>
                <?= $element->getLabelHtml('', $block->getScopeLabel()) ?>
                <div class="admin__field-control control">
                    <?= /* @escapeNotVerified */ ($addOn) ? '<div class="admin__field">' . $element->getElementHtml() . '</div>' : $element->getElementHtml() ?>
                    <?= /* @escapeNotVerified */ $note ?>
                </div>
            <?php endif; ?>
            <div class="field-service">
                <?php if ($block->canDisplayUseDefault()): ?>
                    <label for="<?= $escaper->escapeHtmlAttr($element->getHtmlId()) ?>_default" class="choice use-default">
                        <input <?php if ($element->getReadonly()):?> disabled="disabled"<?php endif; ?>
                            type="checkbox"
                            name="use_default[]"
                            class="use-default-control"
                            id="<?= $escaper->escapeHtmlAttr($element->getHtmlId()) ?>_default"
                            <?php if ($block->usedDefault()): ?> checked="checked"<?php endif; ?>
                            onclick="<?= /* @escapeNotVerified */ $elementToggleCode ?>"
                            value="<?= $escaper->escapeHtmlAttr($block->getAttributeCode()) ?>"
                        />
                        <span class="use-default-label"><?= /* @escapeNotVerified */ __('Use Default Value') ?></span>
                    </label>
                <?php endif ?>
                <?php if ($block->canDisplayUseSystemValue()): ?>
                    <label for="<?= $escaper->escapeHtmlAttr($element->getHtmlId()) ?>_default" class="choice use-default">
                        <input <?php if ($element->getReadonly()):?> disabled="disabled"<?php endif; ?>
                            type="checkbox"
                            name="use_default[]"
                            class="use-default-control"
                            id="<?= $escaper->escapeHtmlAttr($element->getHtmlId()) ?>_default"
                            <?php if ($block->usedSystemValue()): ?> checked="checked"<?php endif; ?>
                            onclick="<?= /* @escapeNotVerified */ $elementToggleCode ?>"
                            value="<?= $escaper->escapeHtmlAttr($block->getAttributeCode()) ?>"
                        />
                        <span class="use-default-label"><?= $escaper->escapeHtml($block->getUseSystemValueLabel()) ?></span>
                    </label>
                <?php endif ?>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
<script>
    require([
        'prototype'
    ], function() {
    });
</script>

