<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<?php
$inputJsConfig = [
    'default' => [
        'show_options' => false,
        'can_be_visibile_in_grid' => true,
        'can_use_wysiwyg' => false,
    ],
    'text' => [
        'can_use_input_validator' => true,
    ],
    'textarea' => [
        'can_use_wysiwyg' => true,
    ],
    'boolean' => [
    ],
    'select' => [
        'show_options' => true,
    ],
    'multiselect' => [
        'show_options' => true,
    ],
    'date' => [
    ],
    'image' => [
    ],
];
?>
<script type="text/x-magento-init">
{
    "*": {
        "Alekseon_AlekseonEav/js/attribute": {
            "frontend_input_default_value": "text",
            "input_types_config": <?= /* @noEscape */ json_encode($inputJsConfig) ?>
        }
    }
}
</script>
