<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
/** @var \Alekseon\AlekseonEav\Block\Adminhtml\Attribute\Edit\Js $block */
?>
<script type="text/x-magento-init">
{
    "*": {
        "Alekseon_AlekseonEav/js/attribute": {
            "frontend_input_default_value": "text",
            "refresh_validators_list": "<?= $block->canRefreshValidatorsList() ?>",
            "input_types_config": <?= /* @noEscape */ $block->getSerializedJsConfig() ?>
        }
    }
}
</script>
