<?php
/**
 * Copyright © Alekseon sp. z o.o.
 * http://www.alekseon.com/
 */
?>
<?php if ($block->displayOptions()): ?>
    <?php $stores = $block->getStores() ?>
    <fieldset class="admin__fieldset fieldset" id="<?php echo $block->getReadOnly() ? 'options_fieldset_read_only' : 'options_fieldset' ?>">
        <legend class="legend">
            <span><?= $block->escapeHtml(__('Manage Options (Values of Your Attribute)')) ?></span>
        </legend>
        <br />
        <div class="admin__control-table-wrapper" id="manage-options-panel" data-index="attribute_options_select_container">
            <table class="admin__control-table" data-index="attribute_options_select">
                <thead>
                    <tr id="attribute-options-table">
                        <th class="col-draggable"></th>
                        <th class="col-default control-table-actions-th">
                            <span><?= $block->escapeHtml(__('Is Default')) ?></span>
                        </th>
                        <?php if ($block->hasOptionCodes()): ?>
                            <th class="col-option-code">
                                <span><?= __('Code') ?></span>
                            </th>
                        <?php endif ?>
                        <?php foreach ($stores as $store): ?>
                            <th<?php if ($store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?> class="_required"<?php endif; ?>>
                                <span><?= $block->escapeHtml(__($store->getName())) ?></span>
                            </th>
                        <?php endforeach; ?>
                        <th class="col-delete">&nbsp;</th>
                        <?php $columnsCounter = count($stores) + 3; ?>
                    </tr>
                </thead>
                <tbody data-role="options-container"></tbody>
                <tfoot>
                <?php if (!$this->getReadOnly()): ?>
                    <tr>
                        <th colspan="<?= (int) $columnsCounter ?>" class="col-actions-add">
                            <button id="add_new_option_button" data-action="add_new_row"
                                    title="<?= $block->escapeHtml(__('Add Option')) ?>"
                                    type="button" class="action- scalable add">
                                <span><?= $block->escapeHtml(__('Add Option')) ?></span>
                            </button>
                        </th>
                    </tr>
                <?php endif ?>
                </tfoot>
            </table>
        </div>
        <script id="row-template" type="text/x-magento-template">
            <tr>
                <td class="col-draggable">
                    <?php if (!$this->getReadOnly()): ?>
                        <div data-role="draggable-handle" class="draggable-handle"
                             title="<?= $block->escapeHtml(__('Sort Option')) ?>">
                        </div>
                        <input data-role="order" type="hidden" name="option[order][<%- data.id %>]"  value="<%- data.sort_order %>" />
                    <?php endif ?>
                </td>
                <td class="col-default control-table-actions-cell">
                    <input class="input-radio" type="<%- data.intype %>" name="default[]" value="<%- data.id %>" <%- data.checked %>/>
                </td>
                <?php if ($block->hasOptionCodes()): ?>
                    <td class="col-option-code">
                        <input name="option[option_code][<%- data.id %>]"
                               value="<%- data.option_code %>"
                               class="input-text"
                                <?php if ($block->getReadOnly()): ?> disabled="disabled"<?php endif;?>
                               type="text"/>
                    </td>
                <?php endif ?>
                <?php foreach ($stores as $store): ?>
                    <td class="col-<%- data.id %>">
                        <input name="option[value][<%- data.id %>][<?= (int)$store->getId() ?>]"
                               value="<%- data.store<?= /* @noEscape */ (int)$store->getId() ?> %>"
                               class="input-text"
                                <?php if ($block->getReadOnly()): ?> disabled="disabled"<?php endif;?>
                               type="text"/>
                    </td>
                <?php endforeach; ?>
                <td id="delete_button_container_<%- data.id %>" class="col-delete">
                    <?php if (!$this->getReadOnly()): ?>
                        <input type="hidden" class="delete-flag" name="option[delete][<%- data.id %>]" value="" />
                        <button id="delete_button_<%- data.id %>"
                                title="<?= $block->escapeHtml(__('Delete')) ?>"
                                type="button"
                                class="action- scalable delete delete-option">
                            <span><?= $block->escapeHtml(__('Delete')) ?></span>
                        </button>
                    <?php endif ?>
                </td>
            </tr>
        </script>
        <?php $values = $block->getOptionValues(); ?>
        <script type="text/x-magento-init">
            {
                "*": {
                    "Alekseon_AlekseonEav/js/attribute/options": {
                        "attributesData": <?= /* @noEscape */ json_encode($values) ?>,
                        "readOnly": <?= (int)$this->getReadOnly() ?>
                    }
                }
            }
        </script>
    </fieldset>
<?php endif ?>
